# Generated by Django 5.1.4 on 2025-05-30 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=123, max_length=150, unique=True, verbose_name='username'),
            preserve_default=False,
        ),
    ]
